name: Release Please

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_please_output: ${{ toJSON(steps.release.outputs) }}
    steps:
      - uses: actions/checkout@v2
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: simplelogworker 
